name: docker

on:
  push:
    branches:
    - main

jobs:
  build-and-release:
    name: build and release docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: containerregistry1982.azurecr.io
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: containerregistry1982.azurecr.io/ttd-backend:${{ github.run_number }}



  deploy:
    name: deploy new image
    needs: [build-and-release]
    runs-on: ubuntu-latest
    steps:
     - name: executing remote SSH commands using password
       uses: appleboy/ssh-action@master
       with:
        host: 52.157.192.99
        username: deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            docker ps -q --filter ancestor="ttd_backend" | xargs -r docker stop
            docker rm -f ttd_backend || true
            docker run -d --name ttd_backend -p3000:3000 -v /home/deploy/data.csv:/app/data.csv containerregistry1982.azurecr.io/ttd-backend:${{ github.run_number }}