name: docker

on:
  push:
    branches:
    - master

jobs:
  build-and-release:
    name: build and release docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: containerregistry1982.azurecr.io
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: containerregistry1982.azurecr.io/ttd-backend:${{ github.run_number }}
